name: checkout and install
description: checkout repository, set up node 20, install dependencies
runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      shell: bash
      run: npm ci