name: cd-workflow

#run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push, workflow_dispatch]

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

  cd-pipeline:
    runs-on: ubuntu-latest
    needs: ci-pipeline

    permissions:
      #  permission to read and push to pages
      pages: write
      id-token: write

    environment: github-pages

    steps:
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: 'dist/'

    - name: deploy pages
      uses: actions/upload-pages-artifact@v3
      with:
        artifact-path: 'dist/'
        target-folder: 'dist/'
        publish-dir: 'dist/'
        token: ${{ secrets.GITHUB_TOKEN }}