name: cd-workflow

#run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push, workflow_dispatch]

jobs:
  cd-pipeline:
    runs-on: ubuntu-latest
    needs: ci-pipeline

    permissions:
      #  permission to read and push to pages
      pages: write
      id-token: write

    environment: github-pages

    steps:
      - name: deploy github pages
        uses: actions/deploy-pages@v4