name: ci-workflow

#run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push, workflow_dispatch]

jobs:
  ci-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: setup nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: run npm scripts as commands in shell
        run: |
          npm ci
          npm run prettier
          npm run typecheck
          npm run test
          npm run build
          echo "All npm scripts have been run"

      - name: upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: 'dist/'

  cd-pipeline:
    runs-on: ubuntu-latest
    needs: ci-workflow

    permissions:
      pages: write
      id-token: write

    environment: github-pages

    steps:
      - name: deploy pages
        uses: actions/deploy-pages@v4
